# kubectl patch deployment -n argocd argocd-server --patch-file argocd/no-tls.yaml
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command: 
          - argocd-server
          - --insecure